# Generated by Django 4.0.6 on 2022-07-14 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(db_index=True, max_length=20)),
                ('lastname', models.CharField(db_index=True, max_length=20)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=14, unique=True)),
                ('acct_id', models.SlugField(default=uuid.UUID('8a2d834b-121f-4021-9a3d-fe2007569b98'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True)),
                ('picture', models.ImageField(default='user.png', null=True, upload_to='uploads/')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='last_login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
                'db_table': 'Accounts',
            },
        ),
    ]
