# Generated by Django 4.0.6 on 2022-07-15 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='organization',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('12d40022-642c-413b-b1f9-2ebb219103c7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='picture',
            field=models.ImageField(default='user.png', null=True, upload_to='uploads'),
        ),
    ]
