# Generated by Django 4.0.6 on 2022-07-15 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0002_accounts_organization_alter_accounts_acct_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('07d2f3ac-1190-4e57-92ca-f30460fce7bf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='organization',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
