# Generated by Django 4.0.6 on 2022-07-15 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0003_alter_accounts_acct_id_alter_accounts_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('2159050f-1a06-4607-8073-238a1d09fe06'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='picture',
            field=models.ImageField(default='uploads/user.png', null=True, upload_to='uploads'),
        ),
    ]
