# Generated by Django 4.0.6 on 2022-07-15 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0004_alter_accounts_acct_id_alter_accounts_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('e087979f-b0b4-42b8-8540-a0569f5d9be4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='firstname',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='lastname',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
