# Generated by Django 4.0.6 on 2022-07-16 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0005_alter_accounts_acct_id_alter_accounts_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('a8b37ee7-bf12-4ab1-b952-eb11d5d76baf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
