# Generated by Django 4.0.6 on 2022-07-16 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0006_alter_accounts_acct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('b0571512-474a-4351-b758-23f016f7b50a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='email address'),
        ),
    ]
