# Generated by Django 4.0.6 on 2022-07-16 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0007_alter_accounts_acct_id_alter_accounts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('7b5f87bb-7d92-4770-b0a9-0b72f3173acc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
