# Generated by Django 4.0.6 on 2022-07-16 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0008_alter_accounts_acct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('eb7a5803-0fe0-4778-ac85-896bef3033b6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
