# Generated by Django 4.0.6 on 2022-07-16 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0009_alter_accounts_acct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('56004aec-991a-40c5-bf13-38806639ad3c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
