# Generated by Django 4.0.6 on 2022-07-17 03:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0010_alter_accounts_acct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('9fa0a8d9-66a9-4c42-9e5f-303a1a49de53'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
