# Generated by Django 4.0.6 on 2022-07-17 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0011_alter_accounts_acct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.SlugField(default=uuid.UUID('eb863f4c-e1c7-4e3c-b18b-80da7c04b6d9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
