# Generated by Django 4.0.6 on 2022-07-17 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_auth', '0012_alter_accounts_acct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acct_id',
            field=models.UUIDField(default=uuid.UUID('f59c3bf6-9dff-4e52-ad62-ac763dfbf160'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
