# Generated by Django 4.0.6 on 2022-07-16 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultInformation',
            fields=[
                ('fullname', models.CharField(max_length=100)),
                ('programme', models.CharField(choices=[('National Diploma', 'ND'), ('Higher National Diploma', 'HND')], max_length=25)),
                ('department', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('cert_no', models.CharField(blank=True, db_index=True, max_length=14, unique=True)),
                ('result_id', models.SlugField(default=uuid.UUID('0e580e0c-97bb-40b0-90c2-4818b1d1959a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Result Information',
                'db_table': 'Result Information',
            },
        ),
    ]
