# Generated by Django 4.0.6 on 2022-07-17 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultInformation',
            fields=[
                ('fullname', models.CharField(max_length=100)),
                ('programme', models.CharField(choices=[('National Diploma', 'ND'), ('Higher National Diploma', 'HND')], max_length=25)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mass Communication', 'Mass Communication'), ('Chemical Engineering', 'Chemical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=100)),
                ('grade', models.CharField(choices=[('Pass', 'Pass'), ('Lower Credit', 'Lower Credit'), ('Upper Credit', 'Upper Credit'), ('Distinction', 'Distinction')], max_length=20)),
                ('cert_no', models.CharField(blank=True, db_index=True, max_length=14, unique=True)),
                ('result_id', models.UUIDField(default=uuid.UUID('f9d5d726-0544-4d6b-85b5-f0fbc0f946db'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Result Information',
                'db_table': 'Result Information',
            },
        ),
    ]
