# Generated by Django 4.0.6 on 2022-07-17 03:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_app', '0003_alter_resultinformation_result_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultinformation',
            name='grade',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Lower Credit', 'Lower Credit'), ('Upper Credit', 'Upper Credit'), ('Distinction', 'Distinction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resultinformation',
            name='result_id',
            field=models.SlugField(default=uuid.UUID('2847230c-f1be-4340-8092-925f81fe6b7e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
