# Generated by Django 4.0.6 on 2022-07-17 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('e_verify_app', '0004_alter_resultinformation_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultinformation',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mass Communication', 'Mass Communication'), ('Chemical Engineering', 'Chemical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resultinformation',
            name='result_id',
            field=models.SlugField(default=uuid.UUID('210ffe47-a9e5-491e-ac77-4798faab4e5a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
